# Generated by Django 4.2.15 on 2024-08-25 20:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import extincteurs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Extincteur",
            fields=[
                (
                    "code",
                    models.CharField(
                        default=extincteurs.models.generate_extincteur_code,
                        editable=False,
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_extincteur",
                    models.CharField(
                        choices=[
                            ("eau", "Eau"),
                            ("mousse", "Mousse"),
                            ("poudre", "Poudre"),
                            ("co2", "CO2"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "classe",
                    models.CharField(
                        choices=[
                            ("A", "Classe A"),
                            ("B", "Classe B"),
                            ("C", "Classe C"),
                            ("D", "Classe D"),
                            ("F", "Classe F"),
                        ],
                        default="A",
                        max_length=2,
                    ),
                ),
                ("date_achat", models.DateField()),
                ("date_valid", models.DateField(default=datetime.date(2024, 8, 24))),
                ("localisation", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "type_inspection",
                    models.CharField(
                        choices=[
                            ("manuelle", "Manuelle"),
                            ("trimestrielle", "Trimestrielle"),
                            ("semestrielle", "Semestrielle"),
                            ("annuelle", "Annuelle"),
                        ],
                        max_length=15,
                    ),
                ),
                ("lieu", models.CharField(max_length=255)),
                ("fiche_controle_verifiee", models.BooleanField(default=False)),
                ("emplacement_correct", models.BooleanField(default=False)),
                ("visible_accessible", models.BooleanField(default=False)),
                ("plaque_lisible", models.BooleanField(default=False)),
                ("signes_deterioration", models.BooleanField(default=False)),
                ("pression_normale", models.BooleanField(default=False)),
                ("mode_emploi_affiche", models.BooleanField(default=False)),
                ("dommage_expose", models.BooleanField(default=False)),
                ("observation", models.TextField(blank=True, null=True)),
                ("prochaine_inspection", models.DateField(blank=True, null=True)),
                (
                    "extincteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="extincteurs.extincteur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.CharField(max_length=10, unique=True)),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=50)),
                ("tel", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("poste", models.CharField(max_length=100)),
                (
                    "type_utilisateur",
                    models.CharField(
                        choices=[("personnel", "Personnel"), ("expert", "Expert")],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RapportInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("pdf", models.FileField(upload_to="media/")),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="extincteurs.inspection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_notification", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField()),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="extincteurs.utilisateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("type_maintenance", models.CharField(max_length=50)),
                ("commentaires", models.TextField(blank=True, null=True)),
                (
                    "expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="extincteurs.utilisateur",
                    ),
                ),
                (
                    "extincteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="extincteurs.extincteur",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inspection",
            name="inspecteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="extincteurs.utilisateur",
            ),
        ),
    ]
