# Generated by Django 4.2.15 on 2024-09-06 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("extincteurs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="maintenance",
            old_name="commentaires",
            new_name="observation",
        ),
        migrations.RemoveField(
            model_name="maintenance",
            name="type_maintenance",
        ),
        migrations.AddField(
            model_name="maintenance",
            name="dommage_expose",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="emplacement_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="fiche_controle_verifiee",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="lieu",
            field=models.CharField(default="emplacement non connu", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="maintenance",
            name="mode_emploi_affiche",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="plaque_lisible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="pression_normale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="prochaine_maintenance",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="signes_deterioration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="visible_accessible",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
